config/routes.rb
CleanWeb::Application.routes.draw do
  resources :usages
  get '/calculation', to: 'calculation#new'
  post '/calculation', to: 'calculation#create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  get '/home', to: 'home#home'

  root to: "home#index"
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :usages
  has_many :variants, class_name: "ActivityVariant"
  validates :name, presence: true
end

app/models/activity_variant.rb
class ActivityVariant < ActiveRecord::Base
  belongs_to :activity
  has_many :usages

  validates :activity, presence: true
  validates :name, presence: true
end

app/models/calculation.rb
class Calculation
  include ActiveModel::Model
  attr_accessor :activity_variant_id, :conversion_id, :quantity, :unit
  delegate :unit, to: :conversion, allow_nil: true

  def activity_variant
    @activity_variant ||= ActivityVariant.find(activity_variant_id) if activity_variant_id
  end

  def conversion
    @conversion ||= Conversion.find(conversion_id) if conversion_id
  end

  def quantity=(input)
    @quantity = BigDecimal.new(input)
  end

  def result
    return nil unless activity_variant && quantity
    conversion.convert(activity_variant.co2 * quantity)
  end

end

app/models/conversion.rb
class Conversion < ActiveRecord::Base

  validates :co2, presence: true
  validates :name, presence: true
  validates :unit, presence: true

  def consumption
    Unit(unit)
  end

  def convert(source_co2)
    source_co2 * co2
  end
end

app/models/usage.rb
class Usage < ActiveRecord::Base
  belongs_to :activity
  belongs_to :activity_variant

  validates :activity, presence: true
  validates :activity_variant, presence: true
  validates :quantity, presence: true
  validates :unit, presence: true

  def consumption
    Unit("#{quantity} #{unit}")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.find_for_facebook_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  respond_to :html

  protected

  def after_sign_in_path_for(resource_or_scope)
    '/calculation'
  end
end

app/controllers/calculation_controller.rb
class CalculationController < ApplicationController
  layout 'calculator'

  def new
    @activities = Activity.all.includes(:variants).load
    @conversions = Conversion.all.load
    @calculation = Calculation.new
  end

  def create
    @activities = Activity.all.includes(:variants).load
    @conversions = Conversion.all.load

    @calculation = Calculation.new(params[:calculation])

    render :new
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # authenticate_user!
    @usage = Usage.new
  end
end

app/controllers/usages_controller.rb
class UsagesController < ApplicationController

  def index
    @usages = Usage.all.includes(:activity, :activity_variant).load
    respond_with @usages
  end

  def new
    @usage = Usage.new
    @activities = Activity.all.load
    @activity_variants = ActivityVariant.all.load

    respond_with @usage
  end

  def create
    @usage = Usage.create permitted_params
    respond_with @usage
  end

  protected

  def permitted_params
    params.require(:usage).permit(:activity_id, :activity_variant_id, :quantity, :unit)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/views/calculation/new.html.slim
article.calculation
  form method="POST"
  = form_for @calculation, url: calculation_path, method: :post do |form|
    section.input
      label Select input
      .control
        = form.grouped_collection_select :activity_variant_id, @activities, :variants, :name, :id, :name, {prompt: true}, class: 'activity_variant'
      .control
        = form.text_field :quantity, class: 'quantity'
        = form.select :unit, ['km', 'ml'], {}, class: 'unit'

    section.output
      label Select output
      .control
        = form.collection_select :conversion_id, @conversions, :id, :name, {prompt: true}, class: 'conversion'

    section.actions
      input type="submit" value="Convert"

  section.result
    .amount
      - if @calculation.result
        - if @calculation.result < 1
          | &lt; 1
        - else
          = @calculation.result.to_i
        | &nbsp;
        = @calculation.unit

app/views/home/index.html.slim
article.landing-home
  header.cars

  section
    h1
      | Become
      strong &nbsp;conscious
      |  of your consumption

    = link_to user_omniauth_authorize_path(provider: 'facebook') do
      = image_tag 'app_facebook.png', class: 'login-button'

    /=render 'usages/form', usage: @usage

app/views/layouts/application.html.slim
doctype html
html
  head
    title CleanWeb
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body

    = yield

    footer
      nav

app/views/layouts/calculator.html.slim
doctype html
html
  head
    title CleanWeb
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag "application", "data-turbolinks-track" => true 
    = csrf_meta_tags 
  body
    header.topbar
      nav
        - if current_user
          img.avatar src="#{current_user.image}"
        h1 ENZIE

    = yield

    footer
      nav

app/views/usages/_form.html.slim
= form_for @usage do |form|
  p= form.collection_select :activity_id, @activities, :id, :name
  p= form.grouped_collection_select :activity_variant_id, @activities, :variants, :name, :id, :name
  p
    = form.number_field :quantity
    = form.label :unit_km
      = form.radio_button :unit, 'km', checked: true
      | km
    = form.label :unit_ml
      = form.radio_button :unit, 'ml'
      | ml
  p= form.submit

app/views/usages/index.html.slim
table
  thead
    tr
      th Activity
      th Variant
      th Consumption
  tbody
    - @usages.each do |usage|
      tr
        td= usage.activity.name
        td= usage.activity_variant.name
        td= usage.consumption

app/views/usages/new.html.slim
= render 'form', usage: @usage